Added vscode debug support

diff --git a/run b/run
--- a/run
+++ b/run
@@ -70,20 +70,14 @@ if [ $# -eq 0 ]; then
     check_if_mac_arm64_and_run_colima
     docker compose up
 else
-    if [ $# -gt 1 ]; then
-        echo "Pass only one argument."
-        exit 1
-    else
-        program_name=$1
-
-        echo -e "Going to compile the latest file: ${GREEN}" $program_name
-        # program_name=$(echo $program_name | sed -r 's/(\.[^.]+$){1}//')   # Removes file extension
-
+    if [ $1 == 'gdb' ]; then
+        program_name=$2
         echo PROGRAM_NAME=$program_name > .env
+        echo -e "Going to compile the latest file: ${GREEN}" $program_name
 
         check_if_mac_arm64_and_run_colima
-        docker compose up
-        
+        docker compose -f docker-compose.debug.yml up
+
         pid=$!
         wait $pid
 
@@ -91,6 +85,30 @@ else
         if echo "$logs" | head -n 2 | grep -q "assembly_environment  | gcc: fatal error: no input files"; then
             echo -e "${RED}You did not pass the correct file to compile."
             exit 1
+        fi
+    else
+        if [ $# -gt 1 ]; then
+            echo "Pass only one argument."
+            exit 1
+        else
+            program_name=$1
+
+            echo -e "Going to compile the latest file: ${GREEN}" $program_name
+            # program_name=$(echo $program_name | sed -r 's/(\.[^.]+$){1}//')   # Removes file extension
+
+            echo PROGRAM_NAME=$program_name > .env
+
+            check_if_mac_arm64_and_run_colima
+            docker compose up
+            
+            pid=$!
+            wait $pid
+
+            logs=$(docker compose logs 2>&1 | tr -d '\0')
+            if echo "$logs" | head -n 2 | grep -q "assembly_environment  | gcc: fatal error: no input files"; then
+                echo -e "${RED}You did not pass the correct file to compile."
+                exit 1
+            fi
         fi
     fi
 fi
